#pragma once

#define SEMITA_PACKET_ID_LIST(X) \
    X(keep_alive, 0) \
    X(login, 1) \
    X(play_status, 2) \
    X(server_to_client_handshake, 3) \
    X(client_to_server_handshake, 4) \
    X(disconnect, 5) \
    X(resource_packs_info, 6) \
    X(resource_pack_stack, 7) \
    X(resource_pack_client_response, 8) \
    X(text, 9) \
    X(set_time, 10) \
    X(start_game, 11) \
    X(add_player, 12) \
    X(add_actor, 13) \
    X(remove_actor, 14) \
    X(add_item_actor, 15) \
    X(server_player_post_move_position, 16) \
    X(take_item_actor, 17) \
    X(move_actor_absolute, 18) \
    X(move_player, 19) \
    X(update_block, 21) \
    X(add_painting, 22) \
    X(level_event, 25) \
    X(block_event, 26) \
    X(actor_event, 27) \
    X(mob_effect, 28) \
    X(update_attributes, 29) \
    X(inventory_transaction, 30) \
    X(mob_equipment, 31) \
    X(mob_armor_equipment, 32) \
    X(interact, 33) \
    X(block_pick_request, 34) \
    X(actor_pick_request, 35) \
    X(player_action, 36) \
    X(hurt_armor, 38) \
    X(set_actor_data, 39) \
    X(set_actor_motion, 40) \
    X(set_actor_link, 41) \
    X(set_health, 42) \
    X(set_spawn_position, 43) \
    X(animate, 44) \
    X(respawn, 45) \
    X(container_open, 46) \
    X(container_close, 47) \
    X(player_hotbar, 48) \
    X(inventory_content, 49) \
    X(inventory_slot, 50) \
    X(container_set_data, 51) \
    X(crafting_data, 52) \
    X(gui_data_pick_item, 54) \
    X(block_actor_data, 56) \
    X(level_chunk, 58) \
    X(set_commands_enabled, 59) \
    X(set_difficulty, 60) \
    X(change_dimension, 61) \
    X(set_player_game_type, 62) \
    X(player_list, 63) \
    X(simple_event, 64) \
    X(legacy_telemetry_event, 65) \
    X(spawn_experience_orb, 66) \
    X(clientbound_map_item_data, 67) \
    X(map_info_request, 68) \
    X(request_chunk_radius, 69) \
    X(chunk_radius_updated, 70) \
    X(game_rules_changed, 72) \
    X(camera, 73) \
    X(boss_event, 74) \
    X(show_credits, 75) \
    X(available_commands, 76) \
    X(command_request, 77) \
    X(command_block_update, 78) \
    X(command_output, 79) \
    X(update_trade, 80) \
    X(update_equip, 81) \
    X(resource_pack_data_info, 82) \
    X(resource_pack_chunk_data, 83) \
    X(resource_pack_chunk_request, 84) \
    X(transfer, 85) \
    X(play_sound, 86) \
    X(stop_sound, 87) \
    X(set_title, 88) \
    X(add_behavior_tree, 89) \
    X(structure_block_update, 90) \
    X(show_store_offer, 91) \
    X(purchase_receipt, 92) \
    X(player_skin, 93) \
    X(sub_client_login, 94) \
    X(automation_client_connect, 95) \
    X(set_last_hurt_by, 96) \
    X(book_edit, 97) \
    X(npc_request, 98) \
    X(photo_transfer, 99) \
    X(modal_form_request, 100) \
    X(modal_form_response, 101) \
    X(server_settings_request, 102) \
    X(server_settings_response, 103) \
    X(show_profile, 104) \
    X(set_default_game_type, 105) \
    X(remove_objective, 106) \
    X(set_display_objective, 107) \
    X(set_score, 108) \
    X(lab_table, 109) \
    X(update_block_synced, 110) \
    X(move_actor_delta, 111) \
    X(set_scoreboard_identity, 112) \
    X(set_local_player_as_initialized, 113) \
    X(update_soft_enum, 114) \
    X(network_stack_latency, 115) \
    X(spawn_particle_effect, 118) \
    X(available_actor_identifiers, 119) \
    X(network_chunk_publisher_update, 121) \
    X(biome_definition_list, 122) \
    X(level_sound_event, 123) \
    X(level_event_generic, 124) \
    X(lectern_update, 125) \
    X(client_cache_status, 129) \
    X(on_screen_texture_animation, 130) \
    X(map_create_locked_copy, 131) \
    X(structure_template_data_request, 132) \
    X(structure_template_data_response, 133) \
    X(client_cache_blob_status, 135) \
    X(client_cache_miss_response, 136) \
    X(education_settings, 137) \
    X(emote, 138) \
    X(multiplayer_settings, 139) \
    X(settings_command, 140) \
    X(anvil_damage, 141) \
    X(completed_using_item, 142) \
    X(network_settings, 143) \
    X(player_auth_input, 144) \
    X(creative_content, 145) \
    X(player_enchant_options, 146) \
    X(item_stack_request, 147) \
    X(item_stack_response, 148) \
    X(player_armor_damage, 149) \
    X(code_builder, 150) \
    X(update_player_game_type, 151) \
    X(emote_list, 152) \
    X(position_tracking_db_server_broadcast, 153) \
    X(position_tracking_db_client_request, 154) \
    X(debug_info, 155) \
    X(packet_violation_warning, 156) \
    X(motion_prediction_hints, 157) \
    X(animate_entity, 158) \
    X(camera_shake, 159) \
    X(player_fog, 160) \
    X(correct_player_move_prediction, 161) \
    X(item_registry, 162) \
    X(clientbound_debug_renderer, 164) \
    X(sync_actor_property, 165) \
    X(add_volume_entity, 166) \
    X(remove_volume_entity, 167) \
    X(simulation_type, 168) \
    X(npc_dialogue, 169) \
    X(edu_uri_resource, 170) \
    X(create_photo, 171) \
    X(update_sub_chunk_blocks, 172) \
    X(sub_chunk, 174) \
    X(sub_chunk_request, 175) \
    X(player_start_item_cooldown, 176) \
    X(script_message, 177) \
    X(code_builder_source, 178) \
    X(ticking_areas_load_status, 179) \
    X(dimension_data, 180) \
    X(agent_action_event, 181) \
    X(change_mob_property, 182) \
    X(lesson_progress, 183) \
    X(request_ability, 184) \
    X(request_permissions, 185) \
    X(toast_request, 186) \
    X(update_abilities, 187) \
    X(update_adventure_settings, 188) \
    X(death_info, 189) \
    X(editor_network, 190) \
    X(feature_registry, 191) \
    X(server_stats, 192) \
    X(request_network_settings, 193) \
    X(game_test_request, 194) \
    X(game_test_results, 195) \
    X(update_client_input_locks, 196) \
    X(camera_presets, 198) \
    X(unlocked_recipes, 199) \
    X(camera_instruction, 300) \
    X(trim_data, 302) \
    X(open_sign, 303) \
    X(agent_animation, 304) \
    X(refresh_entitlements, 305) \
    X(player_toggle_crafter_slot_request, 306) \
    X(set_player_inventory_options, 307) \
    X(set_hud, 308) \
    X(award_achievement, 309) \
    X(clientbound_close_form, 310) \
    X(serverbound_loading_screen, 312) \
    X(jigsaw_structure_data, 313) \
    X(current_structure_feature, 314) \
    X(serverbound_diagnostics, 315) \
    X(camera_aim_assist, 316) \
    X(container_registry_cleanup, 317) \
    X(movement_effect, 318) \
    X(camera_aim_assist_presets, 320) \
    X(client_camera_aim_assist, 321) \
    X(client_movement_prediction_sync, 322) \
    X(update_client_options, 323) \
    X(player_video_capture, 324) \
    X(player_update_entity_overrides, 325) \
    X(player_location, 326) \
    X(clientbound_control_scheme_set, 327) \
    X(debug_drawer, 328) \
    X(serverbound_pack_setting_change, 329) \
    X(clientbound_data_store, 330) \
    X(graphics_override_parameter, 331) \
    X(serverbound_data_store, 332) \
    X(clientbound_data_driven_ui_show_screen, 333) \
    X(clientbound_data_driven_ui_close_screen, 334) \
    X(clientbound_data_driven_ui_reload, 335) \
    X(clientbound_texture_shift, 336) \
    X(voxel_shapes, 337) \
    X(camera_spline, 338) \
    X(camera_aim_assist_actor_priority, 339) \
    X(resource_packs_ready_for_validation, 340) \
    X(locator_bar, 341) \
    X(party_changed, 342) \
    X(serverbound_data_driven_screen_closed, 343) \
    X(sync_world_clocks, 344) \
    X(clientbound_attribute_layer_sync, 345)
