#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>

namespace semita {
    enum class key_state : uint8_t {
        pressed = 1,
        released = 0
    };

    enum class key_type : uint8_t {
        none = 0,

        backspace = 0x08,
        tab = 0x09,
        enter = 0x0D,
        pause = 0x13,
        caps_lock = 0x14,
        escape = 0x1B,
        space = 0x20,

        page_up = 0x21,
        page_down = 0x22,
        end = 0x23,
        home = 0x24,
        left = 0x25,
        up = 0x26,
        right = 0x27,
        down = 0x28,
        insert = 0x2D,
        del = 0x2E,

        d0 = 0x30,
        d1 = 0x31,
        d2 = 0x32,
        d3 = 0x33,
        d4 = 0x34,
        d5 = 0x35,
        d6 = 0x36,
        d7 = 0x37,
        d8 = 0x38,
        d9 = 0x39,

        a = 0x41,
        b = 0x42,
        c = 0x43,
        d = 0x44,
        e = 0x45,
        f = 0x46,
        g = 0x47,
        h = 0x48,
        i = 0x49,
        j = 0x4A,
        k = 0x4B,
        l = 0x4C,
        m = 0x4D,
        n = 0x4E,
        o = 0x4F,
        p = 0x50,
        q = 0x51,
        r = 0x52,
        s = 0x53,
        t = 0x54,
        u = 0x55,
        v = 0x56,
        w = 0x57,
        x = 0x58,
        y = 0x59,
        z = 0x5A,

        numpad_0 = 0x60,
        numpad_1 = 0x61,
        numpad_2 = 0x62,
        numpad_3 = 0x63,
        numpad_4 = 0x64,
        numpad_5 = 0x65,
        numpad_6 = 0x66,
        numpad_7 = 0x67,
        numpad_8 = 0x68,
        numpad_9 = 0x69,
        multiply = 0x6A,
        add = 0x6B,
        subtract = 0x6D,
        decimal = 0x6E,
        divide = 0x6F,

        f1 = 0x70,
        f2 = 0x71,
        f3 = 0x72,
        f4 = 0x73,
        f5 = 0x74,
        f6 = 0x75,
        f7 = 0x76,
        f8 = 0x77,
        f9 = 0x78,
        f10 = 0x79,
        f11 = 0x7A,
        f12 = 0x7B,

        num_lock = 0x90,
        scroll_lock = 0x91,

        shift = 0x10,
        left_control = 0xA2,
        right_control = 0xA3,
        left_alt = 0xA4,
        right_alt = 0xA5,
    };

    inline std::unordered_map<std::string, key_type> key_from_string{
        {"none", key_type::none},
        {"backspace", key_type::backspace},
        {"tab", key_type::tab},
        {"enter", key_type::enter},
        {"pause", key_type::pause},
        {"caps_lock", key_type::caps_lock},
        {"escape", key_type::escape},
        {"space", key_type::space},
        {"page_up", key_type::page_up},
        {"page_down", key_type::page_down},
        {"end", key_type::end},
        {"home", key_type::home},
        {"left", key_type::left},
        {"up", key_type::up},
        {"right", key_type::right},
        {"down", key_type::down},
        {"insert", key_type::insert},
        {"delete", key_type::del},
        {"0", key_type::d0},
        {"1", key_type::d1},
        {"2", key_type::d2},
        {"3", key_type::d3},
        {"4", key_type::d4},
        {"5", key_type::d5},
        {"6", key_type::d6},
        {"7", key_type::d7},
        {"8", key_type::d8},
        {"9", key_type::d9},
        {"a", key_type::a},
        {"b", key_type::b},
        {"c", key_type::c},
        {"d", key_type::d},
        {"e", key_type::e},
        {"f", key_type::f},
        {"g", key_type::g},
        {"h", key_type::h},
        {"i", key_type::i},
        {"j", key_type::j},
        {"k", key_type::k},
        {"l", key_type::l},
        {"m", key_type::m},
        {"n", key_type::n},
        {"o", key_type::o},
        {"p", key_type::p},
        {"q", key_type::q},
        {"r", key_type::r},
        {"s", key_type::s},
        {"t", key_type::t},
        {"u", key_type::u},
        {"v", key_type::v},
        {"w", key_type::w},
        {"x", key_type::x},
        {"y", key_type::y},
        {"z", key_type::z},
        {"numpad_0", key_type::numpad_0},
        {"numpad_1", key_type::numpad_1},
        {"numpad_2", key_type::numpad_2},
        {"numpad_3", key_type::numpad_3},
        {"numpad_4", key_type::numpad_4},
        {"numpad_5", key_type::numpad_5},
        {"numpad_6", key_type::numpad_6},
        {"numpad_7", key_type::numpad_7},
        {"numpad_8", key_type::numpad_8},
        {"numpad_9", key_type::numpad_9},
        {"multiply", key_type::multiply},
        {"add", key_type::add},
        {"subtract", key_type::subtract},
        {"decimal", key_type::decimal},
        {"divide", key_type::divide},
        {"f1", key_type::f1},
        {"f2", key_type::f2},
        {"f3", key_type::f3},
        {"f4", key_type::f4},
        {"f5", key_type::f5},
        {"f6", key_type::f6},
        {"f7", key_type::f7},
        {"f8", key_type::f8},
        {"f9", key_type::f9},
        {"f10", key_type::f10},
        {"f11", key_type::f11},
        {"f12", key_type::f12},
        {"num_lock", key_type::num_lock},
        {"scroll_lock", key_type::scroll_lock},
        {"shift", key_type::shift},
        {"left_control", key_type::left_control},
        {"right_control", key_type::right_control},
        {"left_alt", key_type::left_alt},
        {"right_alt", key_type::right_alt}
    };
}